-- MySQL Script generated by MySQL Workbench
-- Tue Jun 28 12:39:58 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minios` DEFAULT CHARACTER SET utf8 ;
USE `minios` ;

-- -----------------------------------------------------
-- Table `minios`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minios`.`product_type` ;

CREATE TABLE IF NOT EXISTS `minios`.`product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wording` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minios`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minios`.`product` ;

CREATE TABLE IF NOT EXISTS `minios`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_type_id` INT NOT NULL,
  `wording` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_product_type_idx` (`product_type_id` ASC),
  CONSTRAINT `fk_product_product_type`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `minios`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minios`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minios`.`user` ;

CREATE TABLE IF NOT EXISTS `minios`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minios`.`command`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minios`.`command` ;

CREATE TABLE IF NOT EXISTS `minios`.`command` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_commande_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `minios`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minios`.`command_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minios`.`command_product` ;

CREATE TABLE IF NOT EXISTS `minios`.`command_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `command_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_product_commande1_idx` (`command_id` ASC),
  INDEX `fk_commande_product_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_commande_product_commande1`
    FOREIGN KEY (`command_id`)
    REFERENCES `minios`.`command` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `minios`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
